### ISSUE TITLE
KeyError for read ID

### ISSUE THREAD

**Issue by sestaton** [nerettilab/RepEnrich#13]
I'm getting an error when trying to run RepEnrich. Here is the full output of the command:

    Preparing for analysis using RepEnrich...
    Conducting region sorting on unique mapping reads.... 
    Traceback (most recent call last):
      File "/home/statonse/github/RepEnrich/RepEnrich.py", line 145, in <module>
        if not counts.has_key(str(repeat_key[line[3]])):
    KeyError: 'HWI-ST170:244:1:3:5352:18833#0/1'

It's not clear if this is a formatting issue or if the read is not being found. Any input would be appreciated.

**Comment by nskvir** [comment]
Hello,   
Thanks for the notification - the former admin of this project (Steven Criscione) just graduated last month and I've been designated to maintain and update this project in his place.  I'm still familiarizing myself with the repEnrich, but will try to address your issue as soon as I can. 

Best,
Nick

**Comment by kleinpierre** [comment]
Hello, 

I have a similar problem than Sestaton. Any news about that? 

Best, 

Pierre

**Comment by nskvir** [comment]
Hi, sorry I haven't replied to these older threads - I've been busy coding a new version of RepEnrich in which these errors should hopefully be fixed. 

In the meantime, this appears to be similar to the issue seen in this past thread ( https://github.com/nskvir/RepEnrich/issues/5 )  in which the version of bedtools was the culprit.  Be sure the version of bedtools used is prior to 2.24.0 due to an error relating to altered functionality of the coverageBed command. 

Let me know if this helps!

Best,
Nick

**Comment by kleinpierre** [comment]
Hi Nicholas,

Thank you for your help. I tried with betoods 2.23.0. It works fine!

Best,

Pierre


--
Pierre Klein, Ph.D.
Postdoctoral Associate,
Department of Pharmacology
Weill Medical College, Cornell University
1300 York Avenue,
New York, NY 10065
(212) 746-6246 (lab)
(212) 746-6241 (fax)
email: pik2004@med.cornell.edu<mailto:pik2004@med.cornell.edu>



De : Nicholas Skvir <notifications@github.com>
Répondre à : nskvir/RepEnrich <reply@reply.github.com>
Date : mardi 2 mai 2017 à 5:40 PM
À : nskvir/RepEnrich <RepEnrich@noreply.github.com>
Cc : Pierre Klein <pik2004@med.cornell.edu>, Comment <comment@noreply.github.com>
Objet : Re: [nskvir/RepEnrich] KeyError for read ID (#13)


Hi, sorry I haven't replied to these older threads - I've been busy coding a new version of RepEnrich in which these errors should hopefully be fixed.

In the meantime, this appears to be similar to the issue seen in this past thread ( #5<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nskvir_RepEnrich_issues_5&d=DwMFaQ&c=lb62iw4YL4RFalcE2hQUQealT9-RXrryqt9KZX2qu2s&r=vkLqL_z-POmTmCeCzpSTRLpE2GgJq6nSEGHp9HKvc80&m=5L2ExnNGBRhtBsD9WHUtGmKPpVO5exYs9yXE1tVm3Cc&s=iR-yPW97V5vN66YLfPUxN5utqineAdEl-ivM-WHZMUY&e=> ) in which the version of bedtools was the culprit. Be sure the version of bedtools used is prior to 2.24.0 due to an error relating to altered functionality of the coverageBed command.

Let me know if this helps!

Best,
Nick

**Comment by kleinpierre** [comment]
Hi Nicholas,

I’ve seen you released the new version of RepEnrich. I’ve run my data with the previous one and I’m wondering if it is worth to do it again with RepEnrich2. What are the differences between the two versions?

Thanks,

Best,

Pierre


--
Pierre Klein, Ph.D.
Postdoctoral Associate,
Department of Pharmacology
Weill Medical College, Cornell University
1300 York Avenue,
New York, NY 10065
(212) 746-6246 (lab)
(212) 746-6241 (fax)
email: pik2004@med.cornell.edu<mailto:pik2004@med.cornell.edu>



De : Nicholas Skvir <notifications@github.com>
Répondre à : nskvir/RepEnrich <reply@reply.github.com>
Date : mardi 2 mai 2017 à 5:40 PM
À : nskvir/RepEnrich <RepEnrich@noreply.github.com>
Cc : Pierre Klein <pik2004@med.cornell.edu>, Comment <comment@noreply.github.com>
Objet : Re: [nskvir/RepEnrich] KeyError for read ID (#13)


Hi, sorry I haven't replied to these older threads - I've been busy coding a new version of RepEnrich in which these errors should hopefully be fixed.

In the meantime, this appears to be similar to the issue seen in this past thread ( #5<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nskvir_RepEnrich_issues_5&d=DwMFaQ&c=lb62iw4YL4RFalcE2hQUQealT9-RXrryqt9KZX2qu2s&r=vkLqL_z-POmTmCeCzpSTRLpE2GgJq6nSEGHp9HKvc80&m=5L2ExnNGBRhtBsD9WHUtGmKPpVO5exYs9yXE1tVm3Cc&s=iR-yPW97V5vN66YLfPUxN5utqineAdEl-ivM-WHZMUY&e=> ) in which the version of bedtools was the culprit. Be sure the version of bedtools used is prior to 2.24.0 due to an error relating to altered functionality of the coverageBed command.

Let me know if this helps!

Best,
Nick

**Comment by nskvir** [comment]
Hi Pierre,
The primary differences are that the new version utilizes a newer aligner (bowtie2) instead of bowtie, as well as supporting the newer versions of bedtools.  The output is comparable, although RepEnrich2 will return more reads in general across the families/classes due to bowtie2 typically having a better alignment rate to begin with, and also being better equipped to handle longer reads.  

In my trial runs, I've noted higher enrichment across most classes, the exception being the srpRNA class from RepeatMasker.  It appears that a decent proportion of the reads classified as srpRNA from the original RepEnrich are now being mapped to other classes (especially LTR), which we believe may have been an artifact of bowtie1 being geared toward the alignment of shorter reads. 

If you have time to test the new software out, we'd love any feedback as we've only done in-house testing so far on the new version!

Best,
Nick
