### ISSUE TITLE
pre-aligned results as input

### ISSUE THREAD

**Issue by xyouli-zz** [nerettilab/RepEnrich#14]
Hi, I'm trying to use RepEnrich to quantify repeat elements in my RNA-seq data. I'm having some issues with bowtie, mainly low percentage of mapped reads. But I already have bam files from STAR aligner. I'm wondering if I just extract unique mapped reads(sam file) and multimapped reads(fastq file) from this bam file, can RepEnrich accept these as inputs? 

Thanks very much!

**Comment by nskvir** [comment]
Hey there,
The former admin of this project (Steven Criscione) just graduated last month and I've been designated to maintain and update this project in his place.  I'm still familiarizing myself with the repEnrich, but will try to answer your question as soon as I am more acquainted with the program.  

One of the features we will actually be working on in the near future is a new version of RepEnrich that will utilize bowtie2 for better performance in that regard.

Best,
Nick

**Comment by Rhine86** [comment]
Hi. As xyouli mentioned, we could extract unique mapped reads (sam file) and multimapped reads (fastq file) from the bam file that STAR generated. If these files could be used as inputs to RepEnrich?
Thanks！
Yan

**Comment by nskvir** [comment]
Hi Yan, 
I think this should work as long as the fields are the same, although note that STAR and other aligners may have different criteria (such as MAPQ value) for uniquely mapping reads. 

We also currently have a newer version (here: https://github.com/nskvir/RepEnrich2 ) that you may wish to use. It works very similarly but with bowtie2 instead of bowtie. 

Best,
Nick
