### ISSUE TITLE
RepEnrich run time

### ISSUE THREAD

**Issue by aditi-2017** [nerettilab/RepEnrich#17]
Hello, 

Thanks for developing this tool, it works wonderfully! I wanted to ask about the run time of RepEnrich.py script. I have been running it for 2 days using 16 cpus and have started to wonder if this is normal. 

I also wanted to enquire about the version of Biopython needed in this script. 

I will look forward to your reply

Thank you

Aditi

**Comment by nskvir** [comment]
Hello! Thank you for your interest in our project!

I recently took this over from the original creator a few months ago, so I will try to answer your questions to the best of my knowledge.  I have only so far run RepEnrich on a handful of data sets, however the main script usually completes in the ballpark of ~12 hours from what I have seen; this may however be more or less depending on your specific data and the number of repetitive elements contained in your annotation file I believe (I also typically use 16 cpus when running).  If you have any sort of file browser, it's possible to monitor the progress by checking in the temporary output folder where the .bowtie files are generated that correspond to each repetitive element to see how many it has gone through.

As far as the version of Biopython goes, I'm not presently aware of any version-specific dependencies tied to it (although not the case for bedtools for example).  As of taking over the project, I've been using version 1.66 and it seems to work well for me, although I can certainly inquire further if you are having any issues you believe to be related.

I hope this helps! Please don't hesitate if you have any further questions.

Best,
Nick

**Comment by aditi-2017** [comment]
Thank you for your reply ! Runtime is an issue for our system
administrators and they have asked me to split the job so each part
finishes within 24 hours. I have ~48,000 TEs annotated and genome size is ~
1 GB. All the TEs are unclassified (ie. no family or class information) in
repeatmasker output because we used a local library to annotate them. I
hope this is not creating a problem and increasing the run time.

Would it be of any consequence if I split the TE libraries in the setup
folder in smaller sets and then do the mapping ? I can merge the count
files generated afterwards to have a count for all the TEs.

I will look forward to your reply

Aditi

**Comment by nskvir** [comment]
Hi Aditi, 

When you say you have 48,000 TEs annotated, do you mean your locally-annotated repeatmasker file has that many separate entries/lines for TEs in different positions? Or does your setup folder contain 48,000 unique entries?  For instance, the hg19 repeatmasker file (with simple and low complexity repeats removed) used as an example in the documentation has several million entries, but after setup there are only about 1,100 unique pseudogenomes. So far I have only run RepEnrich on this type of data, although if your setup folder has ~40x more entries it could certainly account for the extra running time.

Splitting the TE libraries in the setup folder could conceivably work to shorten the individual times of each run, but it will likely cause bowtie to output many error messages when it can't find the indices you removed, since the repeatmasker and .bam/.fastq alignments would still contain corresponding entries.

As an additional note about your annotation file -- RepEnrich is designed to parse annotation files that include family/class fields. Although it is not necessary to include the actual information if you don't have it, I believe it is still necessary to fill the fields with something (even just with the repeat name or a different arbitrary label) if you haven't done so, as leaving them empty may cause errors. 

I hope this helps!
Nick

**Comment by aditi-2017** [comment]
Thank you for your prompt reply Nick. The setup folder contains 24,211
unique TEs (or pseudogenomes), its a plant genome so we have more TEs. As
long as bowtie finishes running and i get output count file, it will be
okay. Human 3 GB genome with 1,100 TEs finishes in about 12 hours, I will
have to calculate if its feasible for me to do this analysis because I have
12 samples and it might take very long time to finish running these jobs on
our server.

I have not left the columns empty its just filled with text 'unspecified'
so it will seem like all the TEs belong to same class.

Thank you for your help on this matter !

Aditi

**Comment by nskvir** [comment]
No Problem!
