### ISSUE TITLE
GRO-seq

### ISSUE THREAD

**Issue by c-guzman** [nerettilab/RepEnrich#19]
I am looking into using RepEnrich with GRO-seq data.

Is there anything specific that you see may be a problem, or have you tried this before?

EDIT: As an aside, has RepEnrich been fixed to work with bedtools versions 2.24.0+ yet?

**Comment by nskvir** [comment]
Hi there, 
I'm not all that familar with GRO-seq data, so we haven't tried running it before, although from what I read it seems like it might be fine as long as it generates analogous files to use for input to RepEnrich. 

Also, please consider running our newly released RepEnrich2 ( https://github.com/nskvir/RepEnrich2 ) as an alternative -- it supports all versions of bedtools/coverageBed as well as utilizing the newer bowtie2 instead of the original bowtie, while working in a similar way to the first RepEnrich.   Please let us know if you have any issues running (or even if it works great) as it would be very informative!
